version: '3.8'

services:
  order-ecommerce:
    image: order-ecommerce
    build:
      context: .
      dockerfile: Dockerfile
    container_name: order-ecommerce
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    env_file:
      - docker-env-file
    networks:
      - order-ecommerce-local
    restart: always

  postgres:
    image: postgres:latest
    container_name: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=orderecommerce_db
      - POSTGRES_USER=orderecommerceuser
      - POSTGRES_PASSWORD=orderecommercepwd
    volumes:
      - ./setup.sql:/docker-entrypoint-initdb.d/setup.sql
      - postgres-data:/var/lib/postgres
    networks:
      - order-ecommerce-local

  pg_admin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin4
    ports:
      - "15432:80"
    environment:
      - GUNICORN_THREADS=1
      - PGADMIN_DEFAULT_EMAIL=my_awesome_email@email.com
      - PGADMIN_DEFAULT_PASSWORD=does_not_matter
    depends_on:
      - postgres
    networks:
      - order-ecommerce-local

volumes:
  postgres-data:

networks:
  order-ecommerce-local:
    name: order-ecommerce-local
